package com.ordbok.mybatis.model;

import java.util.Date;

public class Ord extends OrdKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.singular_indefinite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String singularIndefinite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.singular_definite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String singularDefinite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.plural_indefinite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String pluralIndefinite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.plural_definite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String pluralDefinite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.imperative
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String imperative;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.infinitive
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String infinitive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.present
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String present;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.past
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String past;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.supine
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String supine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.positive
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String positive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.comparative
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String comparative;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.superlative
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String superlative;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.meaning
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String meaning;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.example
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String example;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.prefix
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String prefix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.suffix
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String suffix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.compound
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String compound;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.category
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.relatedword
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String relatedword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.synonym
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String synonym;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.antonym
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String antonym;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.note
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.created_date
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private Date createdDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.singular_indefinite
	 * @return  the value of ord.singular_indefinite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getSingularIndefinite() {
		return singularIndefinite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.singular_indefinite
	 * @param singularIndefinite  the value for ord.singular_indefinite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setSingularIndefinite(String singularIndefinite) {
		this.singularIndefinite = singularIndefinite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.singular_definite
	 * @return  the value of ord.singular_definite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getSingularDefinite() {
		return singularDefinite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.singular_definite
	 * @param singularDefinite  the value for ord.singular_definite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setSingularDefinite(String singularDefinite) {
		this.singularDefinite = singularDefinite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.plural_indefinite
	 * @return  the value of ord.plural_indefinite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getPluralIndefinite() {
		return pluralIndefinite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.plural_indefinite
	 * @param pluralIndefinite  the value for ord.plural_indefinite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setPluralIndefinite(String pluralIndefinite) {
		this.pluralIndefinite = pluralIndefinite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.plural_definite
	 * @return  the value of ord.plural_definite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getPluralDefinite() {
		return pluralDefinite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.plural_definite
	 * @param pluralDefinite  the value for ord.plural_definite
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setPluralDefinite(String pluralDefinite) {
		this.pluralDefinite = pluralDefinite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.imperative
	 * @return  the value of ord.imperative
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getImperative() {
		return imperative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.imperative
	 * @param imperative  the value for ord.imperative
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setImperative(String imperative) {
		this.imperative = imperative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.infinitive
	 * @return  the value of ord.infinitive
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getInfinitive() {
		return infinitive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.infinitive
	 * @param infinitive  the value for ord.infinitive
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setInfinitive(String infinitive) {
		this.infinitive = infinitive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.present
	 * @return  the value of ord.present
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getPresent() {
		return present;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.present
	 * @param present  the value for ord.present
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setPresent(String present) {
		this.present = present;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.past
	 * @return  the value of ord.past
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getPast() {
		return past;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.past
	 * @param past  the value for ord.past
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setPast(String past) {
		this.past = past;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.supine
	 * @return  the value of ord.supine
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getSupine() {
		return supine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.supine
	 * @param supine  the value for ord.supine
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setSupine(String supine) {
		this.supine = supine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.positive
	 * @return  the value of ord.positive
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getPositive() {
		return positive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.positive
	 * @param positive  the value for ord.positive
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setPositive(String positive) {
		this.positive = positive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.comparative
	 * @return  the value of ord.comparative
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getComparative() {
		return comparative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.comparative
	 * @param comparative  the value for ord.comparative
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setComparative(String comparative) {
		this.comparative = comparative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.superlative
	 * @return  the value of ord.superlative
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getSuperlative() {
		return superlative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.superlative
	 * @param superlative  the value for ord.superlative
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setSuperlative(String superlative) {
		this.superlative = superlative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.meaning
	 * @return  the value of ord.meaning
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getMeaning() {
		return meaning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.meaning
	 * @param meaning  the value for ord.meaning
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setMeaning(String meaning) {
		this.meaning = meaning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.example
	 * @return  the value of ord.example
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getExample() {
		return example;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.example
	 * @param example  the value for ord.example
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setExample(String example) {
		this.example = example;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.prefix
	 * @return  the value of ord.prefix
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getPrefix() {
		return prefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.prefix
	 * @param prefix  the value for ord.prefix
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.suffix
	 * @return  the value of ord.suffix
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getSuffix() {
		return suffix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.suffix
	 * @param suffix  the value for ord.suffix
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.compound
	 * @return  the value of ord.compound
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getCompound() {
		return compound;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.compound
	 * @param compound  the value for ord.compound
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setCompound(String compound) {
		this.compound = compound;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.category
	 * @return  the value of ord.category
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.category
	 * @param category  the value for ord.category
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.relatedword
	 * @return  the value of ord.relatedword
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getRelatedword() {
		return relatedword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.relatedword
	 * @param relatedword  the value for ord.relatedword
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setRelatedword(String relatedword) {
		this.relatedword = relatedword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.synonym
	 * @return  the value of ord.synonym
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getSynonym() {
		return synonym;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.synonym
	 * @param synonym  the value for ord.synonym
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setSynonym(String synonym) {
		this.synonym = synonym;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.antonym
	 * @return  the value of ord.antonym
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getAntonym() {
		return antonym;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.antonym
	 * @param antonym  the value for ord.antonym
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setAntonym(String antonym) {
		this.antonym = antonym;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.note
	 * @return  the value of ord.note
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.note
	 * @param note  the value for ord.note
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.created_date
	 * @return  the value of ord.created_date
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.created_date
	 * @param createdDate  the value for ord.created_date
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
}