package com.ordbok.mybatis.model;

public class OrdKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.ord
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String ord;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ord.partofspeech
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	private String partofspeech;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.ord
	 * @return  the value of ord.ord
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getOrd() {
		return ord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.ord
	 * @param ord  the value for ord.ord
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setOrd(String ord) {
		this.ord = ord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ord.partofspeech
	 * @return  the value of ord.partofspeech
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public String getPartofspeech() {
		return partofspeech;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ord.partofspeech
	 * @param partofspeech  the value for ord.partofspeech
	 * @mbg.generated  Wed Mar 13 13:00:02 HKT 2019
	 */
	public void setPartofspeech(String partofspeech) {
		this.partofspeech = partofspeech;
	}
}